### ISSUE TITLE
errors running aggregate_trips

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/valleybikeData#1]
I'm running into errors trying to run:

```
> trips <- aggregate_trips(full_data)
Error: `:=` can only be used within a quasiquoted argument
Run `rlang::last_error()` to see where the error occurred.
```

Any guidance about what packages need to be loaded for this to work would be appreciated. Thanks in advance, Nick

**Comment by mcgirjau** [comment]
Fixed. The data.table package needed to be imported.
