### ISSUE TITLE
issues with GitHub actions

### ISSUE THREAD

**Issue by nicholasjhorton** [Amherst-Statistics/valleybikeData#2]
@mcgirjau are there any easy fixes to the issues with GitHub actions?  Did I do something wrong on my end?

Thanks in advance for any guidance, Nick

https://github.com/Amherst-Statistics/valleybikeData/runs/2694944170?check_suite_focus=true

**Comment by mcgirjau** [comment]
It's only the Windows check that fails now, but I can't figure out exactly why...

**Comment by mcgirjau** [comment]
Fixed once we moved away from lazy data.

**Comment by nicholasjhorton** [comment]
Many thanks!
